version: '3.8'
services:
  app:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/vendas_app
      - JWT_SECRET=sua_chave_jwt_segura
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
